"""
Appendix: Folio-by-Folio Catalogue with thumbnails.
Generates platypus flowables from folio_catalogue_enriched.json.
"""
import json, os
from reportlab.platypus import Paragraph, Spacer, PageBreak, Table, TableStyle, Image, KeepTogether
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.enums import TA_LEFT

from config import (
    s_h1, s_h2, s_h3, s_body, s_caption, s_table_c, s_table_h,
    gold_rule, blue_rule,
    DARK_NAVY, DEEP_BLUE, MEDIUM_BLUE, ACCENT_BLUE, WARM_GRAY,
    GOLD, DARK_GOLD, LIGHT_GOLD, BORDER, TABLE_HEAD, TABLE_ALT,
    PALE_BLUE, TEXT_W,
)

CATALOGUE_JSON = "d:/tmp/build_paper/folio_catalogue_enriched.json"
IMAGES_DIR = r"D:\Github\Voynich\data\images\pages"

# Compact styles for the catalogue
from reportlab.lib.styles import ParagraphStyle
s_folio_id = ParagraphStyle('FolioID', fontSize=9, leading=11,
    fontName='Helvetica-Bold', textColor=DARK_NAVY)
s_folio_desc = ParagraphStyle('FolioDesc', fontSize=7.5, leading=10,
    fontName='Helvetica', textColor=HexColor("#333333"))
s_folio_disc = ParagraphStyle('FolioDisc', fontSize=7, leading=9,
    fontName='Helvetica-Oblique', textColor=MEDIUM_BLUE)
s_folio_stats = ParagraphStyle('FolioStats', fontSize=7, leading=9,
    fontName='Helvetica', textColor=WARM_GRAY)
s_section_title = ParagraphStyle('SecTitle', fontSize=11, leading=14,
    fontName='Helvetica-Bold', textColor=DEEP_BLUE,
    spaceBefore=5*mm, spaceAfter=2*mm)

SECTION_ORDER = ["T", "H", "A", "C", "Z", "B", "S", "P"]
SECTION_NAMES = {
    "T": "Transitional Pages",
    "H": "Herbal Section (Materia Medica)",
    "A": "Astronomical Diagrams",
    "C": "Cosmological Diagrams & Foldouts",
    "Z": "Zodiac Pages",
    "B": "Balneological Section (Hydrotherapy)",
    "S": "Pharmaceutical Recipes (I)",
    "P": "Pharmaceutical Recipes (II)",
}

THUMB_W = 22 * mm
THUMB_H = 30 * mm


def _get_thumb(image_name):
    """Return an Image flowable or empty string."""
    if not image_name:
        return ""
    path = os.path.join(IMAGES_DIR, image_name)
    if os.path.exists(path):
        try:
            return Image(path, width=THUMB_W, height=THUMB_H)
        except Exception:
            return ""
    return ""


def _make_folio_row(entry):
    """Create a table row for one folio entry."""
    folio = entry["folio"]
    section = entry["section"]
    tier = entry.get("tier", "standard")
    stats = entry["stats"]
    vocab = entry.get("vocabulary", {})

    # Column 1: thumbnail
    thumb = _get_thumb(entry.get("image"))

    # Column 2: folio ID + stats
    tier_marker = {"flagship": "★", "notable": "●", "standard": "○", "minimal": "·"}.get(tier, "")
    id_text = f"{tier_marker} <b>{folio}</b> [{section}]"
    stats_text = (f"Words: {entry['words']} | "
                  f"Perseus: {stats['perseus_pct']}% | "
                  f"CONF+HIGH: {stats['conf_high_pct']}% | "
                  f"Medical: {stats['medical_pct']}%")

    col2 = [
        Paragraph(id_text, s_folio_id),
        Paragraph(stats_text, s_folio_stats),
    ]

    # Column 3: description
    desc_parts = []
    page_desc = entry.get("page_description", "")
    if page_desc:
        desc_parts.append(Paragraph(page_desc, s_folio_desc))

    decoded = entry.get("decoded_subject", "")
    if decoded:
        desc_parts.append(Paragraph(decoded, s_folio_desc))

    # Notable discoveries
    discoveries = entry.get("notable_discoveries", [])
    if discoveries:
        disc_text = " | ".join(discoveries[:2])  # max 2 for space
        desc_parts.append(Paragraph(disc_text, s_folio_disc))

    # Key ingredients
    ingr = vocab.get("ingredients", [])
    ingr_filtered = [i for i in ingr if i not in ("aquam", "aqua")][:6]
    if ingr_filtered:
        desc_parts.append(Paragraph(
            f"<b>Key:</b> {', '.join(ingr_filtered)}", s_folio_stats))

    return thumb, col2, desc_parts


def build_folio_appendix():
    """Build the complete folio catalogue appendix."""
    story = []

    story.append(PageBreak())
    story.append(Paragraph("Appendix A: Folio-by-Folio Catalogue", s_h1))
    story.append(blue_rule())
    story.append(Paragraph(
        "Systematic catalogue of all 226 decoded folio sides. Each entry shows a page "
        "thumbnail, pipeline statistics, and content description generated by the v12 "
        "decoder with AI-assisted review (Claude Code, Anthropic Opus 4.6). "
        "Tier markers: ★ flagship, ● notable, ○ standard, · minimal.",
        s_body))
    story.append(Paragraph(
        "<i>Page images: Yale University, Beinecke Rare Book and Manuscript Library, "
        "MS 408. Used under fair use for academic research.</i>",
        ParagraphStyle('Attrib', fontSize=7.5, leading=10,
            fontName='Helvetica-Oblique', textColor=WARM_GRAY,
            spaceBefore=1*mm, spaceAfter=4*mm)))

    # Load catalogue
    with open(CATALOGUE_JSON, 'r', encoding='utf-8') as f:
        catalogue = json.load(f)

    # Group by section
    by_section = {}
    for entry in catalogue:
        sec = entry["section"]
        by_section.setdefault(sec, []).append(entry)

    for sec_code in SECTION_ORDER:
        entries = by_section.get(sec_code, [])
        if not entries:
            continue

        sec_name = SECTION_NAMES.get(sec_code, sec_code)
        story.append(Paragraph(f"{sec_name} ({len(entries)} folios)", s_section_title))

        # Build table rows
        table_data = []
        for entry in entries:
            thumb, col2_parts, col3_parts = _make_folio_row(entry)

            # Flatten col2 and col3 into single cell content
            col2_cell = col2_parts  # list of Paragraphs
            col3_cell = col3_parts

            table_data.append([thumb, col2_cell, col3_cell])

        # Create table
        col_widths = [THUMB_W + 4*mm, 42*mm, TEXT_W - THUMB_W - 42*mm - 12*mm]
        t = Table(table_data, colWidths=col_widths, repeatRows=0)
        style_cmds = [
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 2),
            ('RIGHTPADDING', (0, 0), (-1, -1), 2),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LINEBELOW', (0, 0), (-1, -1), 0.3, BORDER),
        ]
        # Alternate row backgrounds
        for i in range(len(table_data)):
            if i % 2 == 0:
                style_cmds.append(('BACKGROUND', (0, i), (-1, i), PALE_BLUE))

        t.setStyle(TableStyle(style_cmds))
        story.append(t)

    return story
